insolar/insolar-jepsen

- Dockerfile
- Dockerfile.base
> Docker base image

- config-templates/bootstrap.yaml
- run-test.py
> INS-3227: changed basic balance

- Dockerfile
- config-templates/bootstrap.yaml
What I did:
- added generation migration_addresses.json
> Ins 3248 added fill migration shards on genesis

- config-templates/bootstrap.yaml
What I did:
- Added two params to bootstrap.yaml vesting_pulse_period & lokup_pulse_period
> WLT-882: added params to bootstrap.yaml

- config-templates/bootstrap.yaml
- config-templates/insolar_6.yaml
- config-templates/pulsar.yaml
- config-templates/pulsewatcher.yaml
- run-test.py
Add one not-discovery node to net
> Ins 3364 add not discovery node

- Dockerfile
- config-templates/bootstrap.yaml
- config-templates/insolar_1.yaml
- config-templates/insolar_2.yaml
- config-templates/insolar_3.yaml
- config-templates/insolar_4.yaml
- config-templates/insolar_5.yaml
- config-templates/insolar_6.yaml
- run-test.py
Use pregenerated data for not discovery nodes
> Ins 3365 use pregenerated data for not discovery

- run-test.py
Rewrite test to check that net is down if pulsar is down
> Ins 3412 update pulsar test

- config-templates/bootstrap.yaml
What I did:
added pk_shard_count & ma_shard_count to bootstrap.yaml
> added pk_shard_count and ma_shard_count to bootstrap.yaml

- base-image/Dockerfile
- config-templates/insolar_1.yaml
- config-templates/last_backup_info.json
- run-test.py
The tests for recovery will be in the following PRs.
> INS-3512: enable backups in Jepsen (no recovery tests yet)

- config-templates/insolar_1.yaml
- run-test.py
Still no tests for recovery procedure, see following PRs.
> INS-3512: test incremental backups (step 2)

- run-test.py
If nodes not alive, add pulse watcher output in error log
> Noissue show pulswatcher

- run-test.py
this amount of tests will be used for every PR check in main repo and jepsen repo
> Ins 3581 small tests for pr

- config-templates/bootstrap.yaml
Added fee parameter to bootstrap.yaml
> WLT-1126: added fee parameter to bootstrap.yaml

- run-test.py
Add checking balances form file: total and for every member if needed.
Update test_kill_heavy_under_load to finalize members.
> INS-3550: bench with balaces checkes

- config-templates/insolar_1.yaml
- config-templates/insolar_10.yaml
- config-templates/insolar_11.yaml
- config-templates/insolar_2.yaml
- config-templates/insolar_3.yaml
- config-templates/insolar_4.yaml
- config-templates/insolar_5.yaml
- config-templates/insolar_6.yaml
- config-templates/insolar_7.yaml
- config-templates/insolar_8.yaml
- config-templates/insolar_9.yaml
> INS-3611: availability checker

- run-test.py
Do all transfers with migrated members.
Update option names for benchmark.
> Ins 3566 use migration scenario

- aggregate-logs.py
- config-templates/insolar_1.yaml
> INS-3679: write backupmanager log

- aggregate-logs.py
- config-templates/insolar_1.yaml
- run-test.py
Rewrite jepsen tests for backup daemon, see https://github.com/insolar/insolar/pull/2978
Note: merge only after https://github.com/insolar/insolar/pull/2978 - before merging this PR CI tests will not pass.
> INS-3679: backup daemon

- run-test.py
A new test:  create a backup from existing DB
> INS-3682: create backup from existing db

- base-image/Dockerfile
- run-test.py
How to test:
```
./run-test.py --debug -i insolar-jepsen:latest --others-path .. --skip-all-tests
```
See internal documentation regarding the steps required to build .jar files.
> INS-3736: deploy Java API microservices

- config-templates/insolar_1.yaml
- config-templates/nginx_default.conf
- run-test.py
How to test:
```
./run-test.py --debug -i insolar-jepsen:latest --others-path .. --skip-all-tests
curl -vvv http://localhost:31009/admin-api/rpc/
curl -vvv http://localhost:31009/api/rpc/
curl -vvv http://localhost:31009/api/member/xxx
```
> INS-3736: integrate jepsen deployment with QA tests

- run-test.py
This is required by go-autotests test suite.
> INS-3736: dont run benchmark when --skip-all-tests is used + autopep8

- config-templates/nginx_default.conf
Reverts insolar/insolar-jepsen#85
revert becauase it is fixed in api spec
> Revert "coins api endpoint fix"

- config-templates/insolar_1.yaml
- run-test.py
use rsync instead of backupmanager.
> Ins 3735 backup with rsync

- config-templates/insolar_1.yaml
- config-templates/last_backup_info.json
- run-test.py
1. Set gcrunfrequency: 4 and lightchainlimit: 15
2. Remove last_backup_info from tests
> INS-3794: increase lightchainlimit and gcrunfrequency

- config-templates/observerapi.yaml
added fee to observerapi config
> INS-3848: fee config

- README.md
- base-image/Dockerfile
- config-templates/nginx_default.conf
- run-test.py
everything we havn't migrated is not critical
> remove all java end-points from deployment as migrated most important

- aggregate-logs.py
- run-test.py
> Ins 3810 fix jepsen kill heavy

- config-templates/observerapi.yaml
fixes TestObserverGetToken test
response is fixed by cfg
> add price to cfg

- README.md
- run-test.py
AFAIK no one is using it anyway.
> NOISSUE: get rid of nodeSelector

- config-templates/observer.yaml
- config-templates/observerapi.yaml
> NOISSUE added new params

- config-templates/insolar_1.yaml
- config-templates/insolar_10.yaml
- config-templates/insolar_11.yaml
- config-templates/insolar_2.yaml
- config-templates/insolar_3.yaml
- config-templates/insolar_4.yaml
- config-templates/insolar_5.yaml
- config-templates/insolar_6.yaml
- config-templates/insolar_7.yaml
- config-templates/insolar_8.yaml
- config-templates/insolar_9.yaml
added spec validation config to jepsen
> added openapi spec validation to config

- run-test.py
> INS-3687: skip flaky test

- config-templates/bootstrap.yaml
- config-templates/observerapi.yaml
> WLT-1480: change fee

- Dockerfile
> NOISSUE: remove submodule from dockerfile

- config-templates/insolar_1_postgresql.yaml
- run-test.py
> MN-105: Add --postgresql flag

- config-templates/migrate.yaml
- config-templates/stats-collector.yaml
- run-test.py
> PENV-3: fix jepsens

- run-test.py
> PENV-3: super-puper typo fix

- run-test.py
Reverts insolar/insolar-jepsen#139
> Revert "PENV-3: super-puper typo fix"

- config-templates/migrate.yaml
- config-templates/stats-collector.yaml
- run-test.py
> PENV-3: more observer configs

- config-templates/observerapi.yaml
- run-test.py
update for penv-3 requirements
> Penv 3 configs

- README.md
- run-test.py
Add --public-observer flag to build public observer version
> MN-410: public observer build

- config-templates/insolar_1.yaml
- config-templates/insolar_1_postgresql.yaml
**- What I did**
I have added an auth (required: false) configuration into an exporter. **The tests should work as before with this configuration.**
> MN-486: update exporter config

- config-templates/insolar_1.yaml
- config-templates/insolar_10.yaml
- config-templates/insolar_11.yaml
- config-templates/insolar_1_postgresql.yaml
- config-templates/insolar_2.yaml
- config-templates/insolar_3.yaml
- config-templates/insolar_4.yaml
- config-templates/insolar_5.yaml
- config-templates/insolar_6.yaml
- config-templates/insolar_7.yaml
- config-templates/insolar_8.yaml
- config-templates/insolar_9.yaml
what I did:
- changed specification name for internal api
> MN-651: split specification

- run-test.py
what I did:
- add version validation
> NOISSUE: add version validation
